site_name: YUI's WORLD
site_url: https://fi-0x.github.io/
theme:
  name: material
  custom_dir: docs/overrides #覆写路径
  # font: #谷歌字体，自行搜索
  #   text: Bitter  #文本字体
  #   code: Roboto Mono  #代码字体
  # logo: assets/favicon.png #左上角logo，可插入图片链接

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文

  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo
edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/Fi-0x # 右上角点击跳转的链接
repo_name: YUI # 右上角的名字
nav:
  - 致来者的信: index.md
  - 友链: 友链.md
  -  Weekplan: Objective S2W11.md
  - 周结:
    - S2W8: 周结1.md
    - S2W9: 周结2.md
    - S2W10: 周结3.md
  - Thinking:
    - Self:
        - 分流烦恼: 1.22.md
        - 学习节奏: 2.14.md
        - 生日: 2.26.md
        - ta: 3.2.md
        - 美: 3.20.md
        - 系统周期论: 周期系统论.md
        - 关于惶恐和追求: 关于惶恐和追求.md
        - 开放世界: 人生是个巨大的开放世界游戏.md
        - Schedule: Schedule.md
        - 睡眠不足应对方案: 睡眠不足应对方案.md
        - 关注生命价值: 关注生命价值.md
        - 新时代信息论: 新时代信息论.md
        - 情绪调节: 情绪调节.md
        - 高效休息: 高效休息.md
        - 星露谷物语: 星露谷物语.md
        - 学习的不足: 杂谈--学习的不足.md
    - Relationship:
        - 本科教育: 1.08.md
        - 关于见证: 2.16.md
        - 抽象文化: 3.1抽象.md
        - 刻奇与情绪: 3.23.md
        - 关于大学高中化: 关于大学高中化.md
        - 平行线和相交线: 平行线和相交线谁更可悲.md
        - 生老病死: 生老病死.md
        - 坂本龙一: 坂本龙一.md
        - 定制ai: idea之定制ai.md

  - Views:
    - ali: ali.md
    - study less,learn more: sllm.md
  - Learning routes:
    - Whole: Whole.md
    - Partial:
      - Calculus: Calculus.md
      - Linear Algebra: Linear algebra.md
      - Electric Circuits: Electic Circuit.md
      - Fundamental Physics: Fundamental Physics.md 

  - Occupation plan:
    - 嵌入式方向: 嵌入式方向.md
    - IC方向: IC方向.md

copyright: Copyright &copy; 2024-2025 YUI # 左下角的版权声明
extra:
  generator: true #是否删除页脚显示“使用 MkDocs 材料制造”
  analytics:
    # 网页底部反馈
    feedback:
      title: 此页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline #图标可自定义
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # cookies设置（可选）
extra_javascript:
  - javascripts/extra.js #自定义javascript
  - javascripts/mathjax.js #Latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latex支持
  # - ckplayer/js/ckplayer.js #播放器配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了

extra_css:
  - stylesheets/extra.css # 自定义CSS
  - stylesheets/link.css #友链配置
  - stylesheets/customize.css # 搜索圆角优化

  # - stylesheets/video.css #播放器可选配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  # - ckplayer/css/ckplayer.css   #播放器配置
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持

  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #字体
